from __future__ import annotations

CATEGORY_REGISTRY: dict[str, tuple[str, str]] = {
    # ── Characters ──────────────────────────────────────────────
    "CData_CharacterInfo": ("Characters", "Base Stats"),
    "CData_CharacterLevel": ("Characters", "Progression"),
    "CData_CharacterCamp": ("Characters", "Camp"),
    "CData_CharacterCampSub": ("Characters", "Camp"),
    "CData_CharacterCareer": ("Characters", "Career"),
    "CData_CharacterDamageType": ("Characters", "Combat"),
    "CData_CharacterTag": ("Characters", "Tags"),
    "CData_CharacterTrial": ("Characters", "Trial"),
    "CData_CharacterTrialLevel": ("Characters", "Trial"),
    "CData_CharacterViewMode": ("Characters", "Display"),
    "CData_CharacterLevelLock": ("Characters", "Progression"),
    "CData_CharacterLevelTemplate": ("Characters", "Progression"),
    "CData_LevelTemplate": ("Characters", "Progression"),
    "CData_CharacterBreakAdvanced": ("Characters", "Breakthrough"),
    "CData_BreakAdvanced": ("Characters", "Breakthrough"),
    "CData_CharacterBreakLevelGroup": ("Characters", "Breakthrough"),
    "CData_BreakLevelGroup": ("Characters", "Breakthrough"),
    "CData_BreakSkillGroup": ("Characters", "Breakthrough"),
    "CData_CharacterLimitBreak": ("Characters", "Breakthrough"),
    "CData_CareerLevelCharLocation": ("Characters", "Career"),
    "CData_CareerLevelCharLocationValue": ("Characters", "Career"),
    "CData_CareerLevelValue": ("Characters", "Career"),
    "CData_HeroModify": ("Characters", "Modifications"),
    "CData_LinkCharacterInfo": ("Characters", "Links"),
    "CData_SpineRole": ("Characters", "Display"),
    "CData_InheritLevel": ("Characters", "Inheritance"),
    "CData_AccountLevel": ("Characters", "Account"),
    # ── Skills ──────────────────────────────────────────────────
    "CData_Skill": ("Skills", "Definitions"),
    "CData_SkillBuff": ("Skills", "Effects"),
    "CData_SkillBulletProperty": ("Skills", "Projectiles"),
    "CData_SkillDamage": ("Skills", "Damage"),
    "CData_SkillGroup": ("Skills", "Groups"),
    "CData_RogueSkillGroup": ("Skills", "Rogue Groups"),
    "CData_RogueDynamicSkillGroup": ("Skills", "Rogue Groups"),
    "CData_OverrideSkillGroup": ("Skills", "Groups"),
    "CData_BulletGroup": ("Skills", "Groups"),
    "CData_DmgGroup": ("Skills", "Damage"),
    "CData_SkillPriority": ("Skills", "Priority"),
    "CData_SkillTemplate": ("Skills", "Templates"),
    "CData_SkillTip": ("Skills", "Descriptions"),
    "CData_SkillValue": ("Skills", "Scaling"),
    "CData_AutoBattleGroup": ("Skills", "Auto Battle"),
    "CData_AutoPVEBattle": ("Skills", "Auto Battle"),
    # ── Items & Equipment ──────────────────────────────────────
    "CData_Item": ("Items & Equipment", "Items"),
    "CData_ItemGroup": ("Items & Equipment", "Groups"),
    "CData_GoodsGroup": ("Items & Equipment", "Groups"),
    "CData_SpecialGoodsGroup": ("Items & Equipment", "Groups"),
    "CData_CensorGoodsGroup": ("Items & Equipment", "Groups"),
    "CData_ItemExchange": ("Items & Equipment", "Exchange"),
    "CData_ItemRandompool": ("Items & Equipment", "Random Pools"),
    "CData_Equipment": ("Items & Equipment", "Equipment"),
    "CData_EquipEffect": ("Items & Equipment", "Effects"),
    "CData_EquipEffectGroup": ("Items & Equipment", "Effects"),
    "CData_EquipEffectSlot": ("Items & Equipment", "Slots"),
    "CData_EquipEffectSlotLock": ("Items & Equipment", "Slots"),
    "CData_EquipFightValueGroup": ("Items & Equipment", "Stats"),
    "CData_EquipHeatSlot": ("Items & Equipment", "Heat"),
    "CData_EquipHeatSlotLock": ("Items & Equipment", "Heat"),
    "CData_EquipLevel": ("Items & Equipment", "Leveling"),
    "CData_EquipPos": ("Items & Equipment", "Slots"),
    "CData_EquipQuality": ("Items & Equipment", "Quality"),
    "CData_EquipType": ("Items & Equipment", "Types"),
    # ── Monsters ────────────────────────────────────────────────
    "CData_Monster": ("Monsters", "Definitions"),
    "CData_MonsterGroup": ("Monsters", "Groups"),
    "CData_MonsterLevel": ("Monsters", "Scaling"),
    "CData_MonsterMob": ("Monsters", "Mobs"),
    "CData_MonsterTips": ("Monsters", "Descriptions"),
    "CData_MonsterType": ("Monsters", "Types"),
    "CData_GridEffect": ("Monsters", "Effects"),
    # ── Gacha ───────────────────────────────────────────────────
    "CData_Gacha": ("Gacha", "Banners"),
    "CData_GachaDisplay": ("Gacha", "Display"),
    "CData_GachaGuarantee": ("Gacha", "Pity"),
    "CData_GachaPool": ("Gacha", "Pools"),
    "CData_GachaStep": ("Gacha", "Steps"),
    "CData_GachaTemplate": ("Gacha", "Templates"),
    "CData_GachaWishList": ("Gacha", "Wish List"),
    # ── Story & Cinematics ─────────────────────────────────────
    "CData_Presentation": ("Story & Cinematics", "Presentations"),
    "CData_PresentationBase": ("Story & Cinematics", "Presentations"),
    "CData_PlotPlay": ("Story & Cinematics", "Plot"),
    "CData_PlotStep": ("Story & Cinematics", "Plot"),
    "CData_PlotText": ("Story & Cinematics", "Plot"),
    "CData_AVGDialogue": ("Story & Cinematics", "Dialogue"),
    "CData_BattleCineStep": ("Story & Cinematics", "Battle Cine"),
    "CData_BattleCineSubStep": ("Story & Cinematics", "Battle Cine"),
    "CData_CineDialogueOption": ("Story & Cinematics", "Cinematics"),
    "CData_CineExpressionAnimation": ("Story & Cinematics", "Cinematics"),
    "CData_CineInLoading": ("Story & Cinematics", "Cinematics"),
    "CData_CineRoleFace": ("Story & Cinematics", "Cinematics"),
    "CData_CineVoiceExpression": ("Story & Cinematics", "Cinematics"),
    "CData_BGMStateGroup": ("Story & Cinematics", "BGM"),
    "CData_BGMScene": ("Story & Cinematics", "BGM"),
    "CData_MovieLengthDataNew": ("Story & Cinematics", "Videos"),
    "CData_LoginVideoInfo": ("Story & Cinematics", "Videos"),
    # ── PvE - Main Story ───────────────────────────────────────
    "CData_MainChapter": ("PvE - Story", "Chapters"),
    "CData_MainLevel": ("PvE - Story", "Levels"),
    "CData_MainExplore": ("PvE - Story", "Exploration"),
    "CData_MainExploreReward": ("PvE - Story", "Rewards"),
    "CData_MainBackground": ("PvE - Story", "Backgrounds"),
    "CData_MainLostStory": ("PvE - Story", "Lost Stories"),
    "CData_LevelMapConfig": ("PvE - Story", "Map Config"),
    # ── PvE - Dungeons ─────────────────────────────────────────
    "CData_DungeonChapter": ("PvE - Dungeons", "Chapters"),
    "CData_DungeonLevel": ("PvE - Dungeons", "Levels"),
    "CData_DungeonLevelPhase": ("PvE - Dungeons", "Phases"),
    "CData_PartDungeonChapter": ("PvE - Dungeons", "Part Chapters"),
    "CData_PartDungeonDesc": ("PvE - Dungeons", "Descriptions"),
    "CData_ModuleStageChapter": ("PvE - Dungeons", "Module Stages"),
    "CData_ModuleStageLevel": ("PvE - Dungeons", "Module Stages"),
    # ── PvE - Tower ────────────────────────────────────────────
    "CData_Tower": ("PvE - Tower", "Tower"),
    "CData_TribeTowerLevel": ("PvE - Tower", "Tribe Tower"),
    # ── PvE - Raids ────────────────────────────────────────────
    "CData_HuntingRaidBoss": ("PvE - Raids", "Hunting Raid"),
    "CData_HuntingRaidLevel": ("PvE - Raids", "Hunting Raid"),
    "CData_HuntingRaidRank": ("PvE - Raids", "Hunting Raid"),
    "CData_HuntingRaidReward": ("PvE - Raids", "Hunting Raid"),
    "CData_HuntingRaidAchieve": ("PvE - Raids", "Hunting Raid"),
    "CData_SoloRaidBoss": ("PvE - Raids", "Solo Raid"),
    "CData_SoloRaidLevel": ("PvE - Raids", "Solo Raid"),
    "CData_SoloRaidReward": ("PvE - Raids", "Solo Raid"),
    # ── PvE - Roguelike ────────────────────────────────────────
    "CData_RogueStageChapter": ("PvE - Roguelike", "Chapters"),
    "CData_RogueStageItemCombination": ("PvE - Roguelike", "Items"),
    "CData_RogueStageItemDrop": ("PvE - Roguelike", "Drops"),
    "CData_RogueStageItemInfo": ("PvE - Roguelike", "Items"),
    "CData_RogueStageDropInfo": ("PvE - Roguelike", "Drops"),
    "CData_RogueStageItemRandomGroup": ("PvE - Roguelike", "Items"),
    "CData_RogueStageLevelTips": ("PvE - Roguelike", "Tips"),
    "CData_RogueStageReward": ("PvE - Roguelike", "Rewards"),
    "CData_RogueStageRewardGroup": ("PvE - Roguelike", "Rewards"),
    "CData_RogueTaskAchieve": ("PvE - Roguelike", "Achievements"),
    "CData_RogueTaskAchieveReward": ("PvE - Roguelike", "Achievements"),
    "CData_RogueTechTreeInfo": ("PvE - Roguelike", "Tech Tree"),
    "CData_RogueItemIconPos": ("PvE - Roguelike", "Icons"),
    "CData_RougeItemSubTypeInfo": ("PvE - Roguelike", "Item Types"),
    # ── PvE - Mini Games ───────────────────────────────────────
    "CData_MiniGame108Equipment": ("PvE - Mini Games", "Game 108"),
    "CData_MiniGame108Event": ("PvE - Mini Games", "Game 108"),
    "CData_MiniGame108Guide": ("PvE - Mini Games", "Game 108"),
    "CData_MiniGame108Level": ("PvE - Mini Games", "Game 108"),
    "CData_MiniGameA10CharParts": ("PvE - Mini Games", "Game A10"),
    "CData_MiniGameA10LevelInfo": ("PvE - Mini Games", "Game A10"),
    "CData_MiniGameA10RewardGroup": ("PvE - Mini Games", "Game A10"),
    "CData_MiniGameA10Rewards": ("PvE - Mini Games", "Game A10"),
    "CData_MiniGameA14SlasherLevel": ("PvE - Mini Games", "Game A14"),
    "CData_MiniGameA14SlasherMonster": ("PvE - Mini Games", "Game A14"),
    "CData_MiniGameA14SlasherTask": ("PvE - Mini Games", "Game A14"),
    "CData_MiniGameA3WhackaMoleEnemy": ("PvE - Mini Games", "Game A3"),
    "CData_MiniGameA3WhackaMoleLevel": ("PvE - Mini Games", "Game A3"),
    "CData_MiniGameFlopCardInfo": ("PvE - Mini Games", "Flop Cards"),
    "CData_MiniGameFlopClueInfo": ("PvE - Mini Games", "Flop Cards"),
    "CData_MiniGameFlopClueRewards": ("PvE - Mini Games", "Flop Cards"),
    "CData_MiniGameFlopLevelInfo": ("PvE - Mini Games", "Flop Cards"),
    "CData_MiniGameLegacyStage": ("PvE - Mini Games", "Legacy"),
    "CData_MiniGameRunCubeGroup": ("PvE - Mini Games", "Run"),
    "CData_MiniGameRunLevelCube": ("PvE - Mini Games", "Run"),
    "CData_MiniGameRunLevelFlow": ("PvE - Mini Games", "Run"),
    "CData_MiniGameRunLevelInfo": ("PvE - Mini Games", "Run"),
    "CData_MiniGameTimberLevelInfo": ("PvE - Mini Games", "Timber"),
    # ── PvP ────────────────────────────────────────────────────
    "CData_PVPArenaBuff": ("PvP", "Arena"),
    "CData_PVPMoonArenaBuff": ("PvP", "Moon Arena"),
    "CData_PVPMoonFinalReward": ("PvP", "Moon Arena"),
    "CData_PVPMoonKnockOutReward": ("PvP", "Moon Arena"),
    "CData_PVPMoonPointReward": ("PvP", "Moon Arena"),
    "CData_PVPMoonScore": ("PvP", "Moon Arena"),
    "CData_PVPMoonSeason": ("PvP", "Moon Arena"),
    "CData_PVPMoonShopID": ("PvP", "Moon Arena"),
    "CData_PVPMoonSignReward": ("PvP", "Moon Arena"),
    "CData_PVPNewChallengeCost": ("PvP", "Arena"),
    "CData_PVPNewRank": ("PvP", "Arena"),
    "CData_PVPNewScore": ("PvP", "Arena"),
    "CData_PVPNewScoreReward": ("PvP", "Arena"),
    "CData_PVPSeasonBuff": ("PvP", "Season"),
    "CData_ReplaceArenaRank": ("PvP", "Arena"),
    "CData_ReplaceArenaReward": ("PvP", "Arena"),
    # ── Guild ──────────────────────────────────────────────────
    "CData_GuildBadge": ("Guild", "Customization"),
    "CData_GuildBattle": ("Guild", "Guild Battle"),
    "CData_GuildBattleBoss": ("Guild", "Guild Battle"),
    "CData_GuildBattleDifficulty": ("Guild", "Guild Battle"),
    "CData_GuildBattleGrade": ("Guild", "Guild Battle"),
    "CData_GuildBattleLevel": ("Guild", "Guild Battle"),
    "CData_GuildBattleReward": ("Guild", "Guild Battle"),
    "CData_GuildBattleSubReward": ("Guild", "Guild Battle"),
    "CData_GuildEvent": ("Guild", "Events"),
    "CData_GuildLevel": ("Guild", "Levels"),
    "CData_GuildSign": ("Guild", "Sign"),
    "CData_CouncilHallIssue": ("Guild", "Council Hall"),
    "CData_CouncilHallPosition": ("Guild", "Council Hall"),
    "CData_CouncilHallRoleSize": ("Guild", "Council Hall"),
    "CData_CouncilHallText": ("Guild", "Council Hall"),
    # ── Activities & Events ────────────────────────────────────
    "CData_ActivityMainInfo": ("Activities & Events", "Activities"),
    "CData_ActivitySubInfo": ("Activities & Events", "Activities"),
    "CData_ActivityJumpParam": ("Activities & Events", "Navigation"),
    "CData_Event": ("Activities & Events", "Events"),
    "CData_CirculationType": ("Activities & Events", "Circulation"),
    "CData_CirculationLevel": ("Activities & Events", "Circulation"),
    "CData_ActSignin": ("Activities & Events", "Sign-In"),
    "CData_GoblinLevel": ("Activities & Events", "Goblin"),
    "CData_GoblinReward": ("Activities & Events", "Goblin"),
    "CData_InteractiveGameBotton": ("Activities & Events", "Interactive"),
    "CData_InteractiveGameDialog": ("Activities & Events", "Interactive"),
    # ── Act Sub-Modes ──────────────────────────────────────────
    "CData_ActAfkCharacter": ("Activities & Events", "AFK Mode"),
    "CData_ActAfkGroup": ("Activities & Events", "AFK Mode"),
    "CData_ActAfkSkill": ("Activities & Events", "AFK Mode"),
    "CData_ActAfkBreakThrough": ("Activities & Events", "AFK Mode"),
    "CData_ActAfkLevel": ("Activities & Events", "AFK Mode"),
    "CData_ActAfkTask": ("Activities & Events", "AFK Mode"),
    "CData_ActAfkUpgrade": ("Activities & Events", "AFK Mode"),
    "CData_AFKInstantReward": ("Activities & Events", "AFK Mode"),
    "CData_AFKLevel": ("Activities & Events", "AFK Mode"),
    "CData_ActBuildGameBoss": ("Activities & Events", "Build Game"),
    "CData_ActBuildGameBossReward": ("Activities & Events", "Build Game"),
    "CData_ActBuildGameChapter": ("Activities & Events", "Build Game"),
    "CData_ActBuildGameExtraEffect": ("Activities & Events", "Build Game"),
    "CData_ActBuildGameItem": ("Activities & Events", "Build Game"),
    "CData_ActBuildGameItemTag": ("Activities & Events", "Build Game"),
    "CData_ActBuildGameLevel": ("Activities & Events", "Build Game"),
    "CData_ActExploreInteractive": ("Activities & Events", "Explore"),
    "CData_ActLamiaBonusCha": ("Activities & Events", "Lamia"),
    "CData_ActLamiaLevel": ("Activities & Events", "Lamia"),
    "CData_ActLamiaPowerCha": ("Activities & Events", "Lamia"),
    "CData_ActLostStory": ("Activities & Events", "Lost Story"),
    "CData_ActMemoryChoice": ("Activities & Events", "Memory"),
    "CData_ActMemoryInfo": ("Activities & Events", "Memory"),
    "CData_ActMemoryText": ("Activities & Events", "Memory"),
    "CData_ActTask": ("Activities & Events", "Act Tasks"),
    "CData_ActTaskDailyReward": ("Activities & Events", "Act Tasks"),
    "CData_Act4Clue": ("Activities & Events", "Clue"),
    "CData_AncientCharacter": ("Activities & Events", "Ancient"),
    "CData_AncientTask": ("Activities & Events", "Ancient"),
    # ── Tasks & Achievements ───────────────────────────────────
    "CData_Task": ("Tasks & Achievements", "Tasks"),
    "CData_TaskAchieve": ("Tasks & Achievements", "Achievements"),
    "CData_TaskAchieveReward": ("Tasks & Achievements", "Rewards"),
    "CData_TaskDailyReward": ("Tasks & Achievements", "Daily"),
    "CData_TaskMainReward": ("Tasks & Achievements", "Main"),
    "CData_RewardGroup": ("Tasks & Achievements", "Rewards"),
    "CData_TaskWeeklyReward": ("Tasks & Achievements", "Weekly"),
    "CData_AttractTask": ("Tasks & Achievements", "Attract"),
    "CData_AttractAdd": ("Tasks & Achievements", "Attract"),
    "CData_AttractAddTemplate": ("Tasks & Achievements", "Attract"),
    "CData_AttractArchive": ("Tasks & Achievements", "Attract"),
    "CData_AttractLetter": ("Tasks & Achievements", "Attract"),
    "CData_AttractRank": ("Tasks & Achievements", "Attract"),
    "CData_AttractRankTemplate": ("Tasks & Achievements", "Attract"),
    "CData_AttractStory": ("Tasks & Achievements", "Attract"),
    "CData_AttractStudyRoleSize": ("Tasks & Achievements", "Attract"),
    "CData_AttractTouch": ("Tasks & Achievements", "Attract"),
    "CData_AttractVoiceInfo": ("Tasks & Achievements", "Attract"),
    "CData_AttractVoiceText": ("Tasks & Achievements", "Attract"),
    "CData_MLActionTask": ("Tasks & Achievements", "ML Tasks"),
    # ── Shop & Economy ─────────────────────────────────────────
    "CData_Shop": ("Shop & Economy", "Shop"),
    "CData_ShopGoods": ("Shop & Economy", "Shop"),
    "CData_ShopJumpParam": ("Shop & Economy", "Navigation"),
    "CData_Store": ("Shop & Economy", "Store"),
    "CData_StoreBaseGoodsChapter": ("Shop & Economy", "Store"),
    "CData_StoreBaseGoodsChapterList": ("Shop & Economy", "Store"),
    "CData_StoreBaseGoodsMonthly": ("Shop & Economy", "Store"),
    "CData_StoreMonthlyPrivileges": ("Shop & Economy", "Store"),
    # ── Cosmetics ──────────────────────────────────────────────
    "CData_FashionInfo": ("Cosmetics", "Fashion"),
    "CData_FashionEffects": ("Cosmetics", "Fashion"),
    "CData_FashionSound": ("Cosmetics", "Fashion"),
    "CData_FashionTouch": ("Cosmetics", "Fashion"),
    "CData_FashionVoiceInfo": ("Cosmetics", "Fashion"),
    "CData_FashionVoiceText": ("Cosmetics", "Fashion"),
    "CData_PlayerBackground": ("Cosmetics", "Avatar"),
    "CData_PlayerHead": ("Cosmetics", "Avatar"),
    "CData_PlayerHeadFrame": ("Cosmetics", "Avatar"),
    "CData_Head": ("Cosmetics", "Avatar"),
    "CData_LoungeChar": ("Cosmetics", "Lounge"),
    "CData_LoungeCharIdle": ("Cosmetics", "Lounge"),
    "CData_LoungeCharParts": ("Cosmetics", "Lounge"),
    "CData_LoungeCharProcess": ("Cosmetics", "Lounge"),
    "CData_LoungeItem": ("Cosmetics", "Lounge"),
    "CData_LoungeValueLevel": ("Cosmetics", "Lounge"),
    # ── Castle ─────────────────────────────────────────────────
    "CData_CastleDispatchLevel": ("Castle", "Dispatch"),
    "CData_CastleDispatchLocation": ("Castle", "Dispatch"),
    "CData_CastleDispatchEvent": ("Castle", "Dispatch"),
    "CData_CastlePlace": ("Castle", "Placement"),
    "CData_CastleStarInfo": ("Castle", "Stars"),
    "CData_CastleStarTech": ("Castle", "Stars"),
    "CData_CastleStatue": ("Castle", "Statues"),
    "CData_CastleStatueLevel": ("Castle", "Statues"),
    "CData_CastleStoryInfo": ("Castle", "Story"),
    "CData_CastleStoryPerform": ("Castle", "Story"),
    # ── Legacy Mode ────────────────────────────────────────────
    "CData_Legacy": ("Legacy Mode", "Base"),
    "CData_LegacyEnemyLine": ("Legacy Mode", "Dialogue"),
    "CData_LegacyGameSkill": ("Legacy Mode", "Skills"),
    "CData_LegacyLevel": ("Legacy Mode", "Levels"),
    "CData_LegacyStageArea": ("Legacy Mode", "Stages"),
    "CData_LegacyStageChapterInfo": ("Legacy Mode", "Stages"),
    "CData_LegacyStageCharacter": ("Legacy Mode", "Stages"),
    "CData_LegacyStageInteractive": ("Legacy Mode", "Stages"),
    "CData_LegacyStageLevelInfo": ("Legacy Mode", "Stages"),
    "CData_LegacyStageLevelTips": ("Legacy Mode", "Stages"),
    "CData_LegacyStageMonster": ("Legacy Mode", "Stages"),
    # ── Localization ───────────────────────────────────────────
    "CData_MultiLanguage": ("Localization", "Languages"),
    "CData_MultiLanguagePic": ("Localization", "Languages"),
    "CData_AllLanguageTemplete": ("Localization", "Templates"),
    "CData_CommonText": ("Localization", "Text"),
    "CData_InitLangTxt": ("Localization", "Text"),
    "CData_FallbackLanguage": ("Localization", "Fallback"),
    "CData_UILanguage": ("Localization", "UI"),
    # ── System & UI ────────────────────────────────────────────
    "CData_SystemUnlock": ("System & UI", "Unlocks"),
    "CData_Jump": ("System & UI", "Navigation"),
    "CData_GuideStep": ("System & UI", "Tutorial"),
    "CData_GuideSubStep": ("System & UI", "Tutorial"),
    "CData_TutorialTips": ("System & UI", "Tutorial"),
    "CData_PicGuide": ("System & UI", "Tutorial"),
    "CData_ClientMessage": ("System & UI", "Messages"),
    "CData_ConfirmCommonTips": ("System & UI", "Dialogs"),
    "CData_ShowMessage": ("System & UI", "Messages"),
    "CData_SettingGraphicsChoice": ("System & UI", "Settings"),
    "CData_SettingGraphicsInfo": ("System & UI", "Settings"),
    "CData_SettingLanguage": ("System & UI", "Settings"),
    "CData_SettingPush": ("System & UI", "Settings"),
    "CData_KeyboardMapping": ("System & UI", "Input"),
    "CData_Property": ("System & UI", "Properties"),
    "CData_PropertyIndex": ("System & UI", "Properties"),
    "CData_AttributeLimit": ("System & UI", "Limits"),
    "CData_StandardBattleValue": ("System & UI", "Battle Values"),
    "CData_GameScene": ("System & UI", "Scenes"),
    "CData_LineUpRecommend": ("System & UI", "Formation"),
    "CData_StarParm": ("System & UI", "Stars"),
    "CData_MoonType": ("System & UI", "Moon Types"),
    "CData_GlobalSettings": ("System & UI", "Global"),
    "CData_EditorExportSetting": ("System & UI", "Editor"),
    "CData_ResourcesCheckSwitch": ("System & UI", "Resources"),
    "CData_RegionMapping": ("System & UI", "Regions"),
    # ── Battle System ──────────────────────────────────────────
    "CData_BattleWorld": ("Battle System", "Worlds"),
    "CData_BattleWorldConfig": ("Battle System", "Worlds"),
    "CData_BattleDefeatPrompt": ("Battle System", "UI"),
    "CData_BattleGlobalEffect": ("Battle System", "Effects"),
    "CData_BattleMD5": ("Battle System", "Checksums"),
    "CData_BattleMode": ("Battle System", "Modes"),
    "CData_BattleRepress": ("Battle System", "Mechanics"),
    "CData_BattleResultCondition": ("Battle System", "Victory"),
    "CData_BattleResultIndex": ("Battle System", "Victory"),
    "CData_ResultConditionType": ("Battle System", "Victory"),
    "CData_GridEffect": ("Battle System", "Grid"),
    # ── Audio ──────────────────────────────────────────────────
    "CData_ActionSoundEffects": ("Audio", "Action SFX"),
    "CData_TimelineSoundEffects": ("Audio", "Timeline SFX"),
    "CData_UISfxes": ("Audio", "UI SFX"),
    "CData_WwiseSoundbanksInfo": ("Audio", "Soundbanks"),
    # ── Ranks & Rewards ────────────────────────────────────────
    "CData_RankInfo": ("Ranks & Rewards", "Ranks"),
    "CData_RankCollectReward": ("Ranks & Rewards", "Rewards"),
    "CData_RankTargetReward": ("Ranks & Rewards", "Rewards"),
    # ── Search ─────────────────────────────────────────────────
    "CData_SearchGridType": ("Search", "Grid"),
    "CData_SearchHitItem": ("Search", "Hits"),
    "CData_SearchHitMap": ("Search", "Hits"),
    "CData_SearchLevel": ("Search", "Levels"),
    "CData_SearchRank": ("Search", "Ranks"),
    "CData_SearchEvent": ("Search", "Events"),
    # ── Mail ───────────────────────────────────────────────────
    "CData_MailTemplate": ("Mail", "Templates"),
    # ── Misc ───────────────────────────────────────────────────
    "CData_GMCommand": ("Misc", "GM"),
    "CData_GMShortcuts": ("Misc", "GM"),
}


def get_category(class_name: str) -> tuple[str, str]:
    if class_name in CATEGORY_REGISTRY:
        return CATEGORY_REGISTRY[class_name]
    return ("Other", "Uncategorized")
